# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.category_manager:
            class: AppBundle\Manager\CategoryManager
            arguments:
              - "@doctrine.orm.entity_manager"

    app.task_manager:
            class: AppBundle\Manager\TaskManager
            arguments:
              - "@doctrine.orm.entity_manager"

    salavert.twig.time_ago:
        class: Salavert\Twig\Extension\TimeAgoExtension
        arguments: ["@translator"]
        tags:
            - { name: twig.extension }